# Render Blueprint for Digital Footprint Analyzer

services:
  # Web Service
  - type: web
    name: digital-footprint-analyzer
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.0-flash-exp
      - key: EXA_API_KEY
        sync: false
      - key: APIFY_API_TOKEN
        sync: false
      - key: DATABASE_PATH
        value: /var/data/tokens.db
      - key: ALLOWED_ORIGINS
        value: https://profile-builder.onrender.com
      - key: OAUTH_REDIRECT_URI
        value: https://profile-builder.onrender.com/oauth2callback
      - key: ENABLE_LLM_ANALYSIS
        value: false
      - key: LLM_MAX_EMAILS_TO_ANALYZE
        value: 10
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1

